### PR TITLE
fixes #1

### LINKED ISSUE #1: Javascript error
Won't work as expected.

```
TypeError: rules is not iterabletr_TR:604:39
    <anonymous> http://bk.it/tr_TR/:604
```

```javascript
const [successCookieDuration] = rules;
```

Possible solution:
```javascript
//turns rules to an array
let _rules = JSON.parse(popup.getAttribute('data-popup-rules'));
const rules = Object.keys(_rules).map(i => _rules[i]);
```

### PR DESCRIPTION
**Pull request by htaoufikallah**

### CODE REVIEW

**Comment by delirehberi** [comment]
problem solved in the database layer, you can fetch master branch for updated code.

**Comment by htaoufikallah** [comment]
I just try it it doesn't work for me
In the db it is saved like this: {"workouse_popup_plugin.ui.success_cookie_duration":"successCookieDuration"}
In the the form it is displayed correctly with the translation value not the id
And in the rendered html it is rendered like this: 
`<div id="popup" data-popup-id="2" data-popup-rules="{&quot;workouse_popup_plugin.ui.success_cookie_duration&quot;:&quot;successCookieDuration&quot;}"></div>`

And here is the js error I get now:
Uncaught TypeError: Invalid attempt to destructure non-iterable instance

for now I'm overriding that template code with this workaround:
const successCookieDuration = rules['workouse_popup_plugin.ui.success_cookie_duration'];

Tell me if I'm missing something.

by the way from the js behaviour I think that this rule should be renamed to "show only once" or I'm missing something :) WYT?

**Comment by bykclk** [comment]
Thank you for feedback. You are right i fixed the error with this https://github.com/workouse/popup-sylius/commit/08448678ec8bdae9e3d5d69ef94f0880e625d0a8 commit. If the problem persists please let us know.

**Comment by htaoufikallah** [comment]
@bykclk it works now thx
I'll ask again about name of this rule shouldn't it be renamed to "show only once" or something else meaningful because that's what it does unless I'm missing something. WYT?

**Comment by bykclk** [comment]
@htaoufikallah Yes, you are right, this naming is wrong. When I first did this, I thought differently, it could specify a time to show it back, but since I did not need it, I did it only show the user once, but I forgot to change the naming, if you think a better naming, you can change it without hesitation and share it with us.

**Comment by htaoufikallah** [comment]
@bykclk sorry for my late response. I just submitted a PR #4

**Comment by bykclk** [comment]
Thank you for contribution

**Pull request closed without merging**
