### PR TITLE
add support for friendsofsymfony/ckeditor-bundle version 2

### PR DESCRIPTION
**Pull request by htaoufikallah**

### CODE REVIEW

**Comment by bykclk** [comment]
thank you for contribution but Since FOSCKEditorBundle 2.0, to make Twig render the WYSIWYG editor, you must add some configuration under the `twig.form_themes` config key:
```yaml
# config/packages/twig.yaml

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
```
and you need to update readme.md

**Comment by htaoufikallah** [comment]
@bykclk done

**Comment by bykclk** [comment]
Thank you

**Comment by htaoufikallah** [comment]
@bykclk you are welcome :)

**Pull request merged**
